<a href="https://colab.research.google.com/github/Barsha-gc/Concept-and-technologies-of-AI/blob/main/Workshop1ipynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

# 1. Initialize an empty array with size 2x2
arr_empty = np.empty((2, 2))
print("1. Empty 2x2 array:\n", arr_empty)


# 2. Initialize an all-one array with size 4x2
arr_ones = np.ones((4, 2))
print("\n2. All ones 4x2 array:\n", arr_ones)


# 3. Return a new array of given shape and type, filled with a fill value
arr_full = np.full((3, 3), 7)  # Example: fill with 7
print("\n3. Full 3x3 array filled with 7:\n", arr_full)


# 4. Return a new array of zeros with same shape and type as a given array
a = np.array([[1, 2], [3, 4]])
arr_zeros_like = np.zeros_like(a)
print("\n4. Zeros like given array a:\n", arr_zeros_like)


# 5. Return a new array of ones with same shape and type as a given array
b = np.array([[5, 6], [7, 8]])
arr_ones_like = np.ones_like(b)
print("\n5. Ones like given array b:\n", arr_ones_like)


# 6. Convert an existing list to a numpy array
new_list = [1, 2, 3, 4]
arr_from_list = np.array(new_list)
print("\n6. Array from list:\n", arr_from_list)


1. Empty 2x2 array:
 [[5.45843428e-315 0.00000000e+000]
 [4.94065646e-324             nan]]

2. All ones 4x2 array:
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

3. Full 3x3 array filled with 7:
 [[7 7 7]
 [7 7 7]
 [7 7 7]]

4. Zeros like given array a:
 [[0 0]
 [0 0]]

5. Ones like given array b:
 [[1 1]
 [1 1]]

6. Array from list:
 [1 2 3 4]
